apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp1
  labels:
    app: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:    
      containers:
      - name: dp1
        image: amansingh12/dream_web
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dp-servie
spec:
  selector:
    app: test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
