apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: test
spec:
  containers:
  - name: pod1
    image: amansingh12/shopping_page:latest
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
 name: pod-service

spec:
 selector:
   app: test
 ports:
 - protocol: TCP
   port: 80
 type: NodePort
