#  k create secret generic imp-sec --from-literal=username=Amansingh --from-literal=password=Aman@1234 --from-literal=ubuntu_version=20.8.4
this command first to create the sceret then we will use in the pod
apiVersion: v1
kind: Pod
metadata:
  name: sc1
spec:
  containers:
  - name: sc1
    image: nginx
    env:
    - name: username
      valueFrom:
        secretKeyRef:
          name: db-sceret
          key: username
