types of secret we have to study :-

Built-in                                               Type	Usage
Opaque	                                          arbitrary user-defined data
kubernetes.io/service-account-token	              ServiceAccount token
kubernetes.io/dockercfg	                          serialized ~/.dockercfg file
kubernetes.io/dockerconfigjson	                   serialized ~/.docker/config.json file
kubernetes.io/basic-auth	                         credentials for basic authentication
kubernetes.io/ssh-auth	                           credentials for SSH authentication
kubernetes.io/tls	                                 data for a TLS client or server
bootstrap.kubernetes.io/                           token	bootstrap token data



#  k create secret generic imp-sec --from-literal=username=Amansingh --from-literal=password=Aman@1234 --from-literal=ubuntu_version=20.8.4
this command first to create the sceret then we will use in the pod
apiVersion: v1
kind: Pod
metadata:
  name: sc1
spec:
  containers:
  - name: sc1
    image: nginx
    env:
    - name: username
      valueFrom:
        secretKeyRef:
          name: db-sceret
          key: username




# CREATE A SECRET FOR THE DOCKER REGISTRY AND PULL THE PRIVATE IMAGE FROM THE DOCKER HUB WITH USING THE DOCKER SECRET CREATED IN CLUSTER OF K8S 



apiVersion: v1
kind: Pod
metadata:
  name: docker-private
  labels: 
    app: test
spec:
  containers:
  - name: docker-image
    image: amansingh12/private:preface
  imagePullSecrets:
  - name: docker-secret

---

apiVersion: v1
kind: Service
metadata:
 name: pod-service
 labels:
   app: test
spec: 
  conatiners:
  - name: docker-pod
    image: amansingh12/private:preface
  imagePullSecrets:
  - name: docker-secret

---
apiVersion: v1
kind: Service
metadata:
  name: docker-service
spec:
  selector:
     app: test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
    



          
