apiVersion: v1
kind: Secret
metadata:
  name: file-secret
data:
  secret-file: QW1hblNpbmdo
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-files-pod
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: file-secret
  containers:
    - name: nginx1
      image: nginx
      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/usr/secret-volume"

          # to mount the volume in the pods with using secret file
